### ISSUE TITLE
Conda Permissions Issue

### ISSUE THREAD

**Issue by ymt123** [Lab41/nbserver#35]
There is a permissions issue with the conda directory for new containers. 

sudo chown <username> -R /opt/conda does resolve it but we should try to figure out what caused it/update the docker container so new users don't hit it.

**Comment by agude** [comment]
I first noticed this when trying to fix #32 (with #34).

It seems to have the following behavior for me: I can install with conda once, but every subsequent install fails with the permission error. I'll try to see if that's true.

I fixed it in my local container by deleting the cache directory (`/opt/conda/cache` I think) and then remaking it with 777 permissions.

**Comment by ymt123** [comment]
I wonder if it's tied to the late install of "six" (it happens in the deep learning container). The other conda installs clean up afterwards. Do you think it's worth moving the install to earlier in the build chain?

**Comment by agude** [comment]
That seems likely; I don't recall the issue before putting that in.

**Comment by agude** [comment]
Here is the full error:

```conda install django
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.0.12
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.2 Linux/3.13.0-101-generic debian/jessie/sid glibc/2.19
                UID:GID : 1230:4100



`$ /opt/conda/bin/conda install django`




    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 494, in <listcomp>
        for url, schan, pri in tasks]
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 143, in func
        res = f(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/index.py", line 481, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/opt/conda/pkgs/cache/db552c1e.json'```

**Comment by agude** [comment]
Running `sudo /opt/conda/bin/conda clean -tipsy` fixes it; I suspect we just need to add this to the container after the six install.
